# Generated by Django 4.1 on 2023-10-19 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('tipo_endereco', models.CharField(blank=True, choices=[('UNI', 'Único'), ('RES', 'Residencial'), ('COM', 'Comercial'), ('COB', 'Cobrança'), ('ENT', 'Entrega'), ('OUT', 'Outro')], max_length=3, null=True, verbose_name='Tipo')),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=16, null=True, verbose_name='Numero')),
                ('bairro', models.CharField(blank=True, max_length=64, null=True, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=64, null=True, verbose_name='complemento')),
                ('municipio', models.CharField(blank=True, max_length=64, null=True, verbose_name='Municipio')),
                ('cep', models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('EX', 'EX'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='SP', max_length=3, null=True, verbose_name='UF')),
                ('cliente_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='clientes.clientes', verbose_name='Cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
