# Generated by Django 4.1 on 2023-10-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Documento')),
                ('whatsApp', models.CharField(max_length=50, verbose_name='WhatsApp')),
                ('tipo_cliente', models.CharField(choices=[('normal', 'Normal'), ('contrato', 'Contrato')], default='normal', max_length=30)),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
