# Generated by Django 4.1 on 2023-10-20 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='validade',
            field=models.DateField(default=datetime.date(2023, 11, 6), verbose_name='Validade'),
        ),
    ]
