# Generated by Django 4.1 on 2023-10-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0002_alter_orcamento_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduto',
            name='calculo_produtos',
            field=models.CharField(choices=[(0, 'Porcentagem'), (1, 'Valor')], default=0, max_length=2, verbose_name='Forma de Calculo'),
        ),
    ]
