# Generated by Django 4.1 on 2023-10-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0005_orcamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproduto',
            name='tipo_calculo',
            field=models.CharField(default=0, max_length=1, verbose_name='Tipo de Calculo'),
        ),
    ]
