# Generated by Django 4.1 on 2023-10-20 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('orcamentos', '0006_itemproduto_tipo_calculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_orcamento', to='base.empresa', verbose_name='Empresa'),
        ),
    ]
