# Generated by Django 4.2.6 on 2023-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0007_alter_orcamento_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='status',
            field=models.CharField(default='0', max_length=1, verbose_name='Status'),
        ),
    ]
