# Generated by Django 4.2.6 on 2023-10-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0008_alter_orcamento_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemproduto',
            name='calculo_produtos',
        ),
        migrations.AddField(
            model_name='itemproduto',
            name='lucro_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Lucro venda'),
        ),
    ]
