# Generated by Django 4.2.6 on 2023-10-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0009_remove_itemproduto_calculo_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduto',
            name='tipo_calculo',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Tipo de Calculo'),
        ),
    ]
