# Generated by Django 4.2.6 on 2023-10-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcamentos', '0010_alter_itemproduto_tipo_calculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
